// <auto-generated />
using Exchange.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exchange.Data.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Exchange.Models.Menjacnica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Base")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("disclaimer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ratesId")
                        .HasColumnType("int");

                    b.Property<int>("timestamp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ratesId");

                    b.ToTable("Menjacnica");
                });

            modelBuilder.Entity("Exchange.Models.Rates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("AED")
                        .HasColumnType("double");

                    b.Property<double>("AFN")
                        .HasColumnType("double");

                    b.Property<double>("ALL")
                        .HasColumnType("double");

                    b.Property<double>("AMD")
                        .HasColumnType("double");

                    b.Property<double>("ANG")
                        .HasColumnType("double");

                    b.Property<double>("AOA")
                        .HasColumnType("double");

                    b.Property<double>("ARS")
                        .HasColumnType("double");

                    b.Property<double>("AUD")
                        .HasColumnType("double");

                    b.Property<double>("AWG")
                        .HasColumnType("double");

                    b.Property<double>("AZN")
                        .HasColumnType("double");

                    b.Property<double>("BAM")
                        .HasColumnType("double");

                    b.Property<int>("BBD")
                        .HasColumnType("int");

                    b.Property<double>("BDT")
                        .HasColumnType("double");

                    b.Property<double>("BGN")
                        .HasColumnType("double");

                    b.Property<double>("BHD")
                        .HasColumnType("double");

                    b.Property<double>("BIF")
                        .HasColumnType("double");

                    b.Property<int>("BMD")
                        .HasColumnType("int");

                    b.Property<double>("BND")
                        .HasColumnType("double");

                    b.Property<double>("BOB")
                        .HasColumnType("double");

                    b.Property<double>("BRL")
                        .HasColumnType("double");

                    b.Property<int>("BSD")
                        .HasColumnType("int");

                    b.Property<double>("BTC")
                        .HasColumnType("double");

                    b.Property<double>("BTN")
                        .HasColumnType("double");

                    b.Property<double>("BWP")
                        .HasColumnType("double");

                    b.Property<double>("BYN")
                        .HasColumnType("double");

                    b.Property<double>("BZD")
                        .HasColumnType("double");

                    b.Property<double>("CAD")
                        .HasColumnType("double");

                    b.Property<double>("CDF")
                        .HasColumnType("double");

                    b.Property<double>("CHF")
                        .HasColumnType("double");

                    b.Property<double>("CLF")
                        .HasColumnType("double");

                    b.Property<double>("CLP")
                        .HasColumnType("double");

                    b.Property<double>("CNH")
                        .HasColumnType("double");

                    b.Property<double>("CNY")
                        .HasColumnType("double");

                    b.Property<double>("COP")
                        .HasColumnType("double");

                    b.Property<double>("CRC")
                        .HasColumnType("double");

                    b.Property<int>("CUC")
                        .HasColumnType("int");

                    b.Property<double>("CUP")
                        .HasColumnType("double");

                    b.Property<double>("CVE")
                        .HasColumnType("double");

                    b.Property<double>("CZK")
                        .HasColumnType("double");

                    b.Property<double>("DJF")
                        .HasColumnType("double");

                    b.Property<double>("DKK")
                        .HasColumnType("double");

                    b.Property<double>("DOP")
                        .HasColumnType("double");

                    b.Property<double>("DZD")
                        .HasColumnType("double");

                    b.Property<double>("EGP")
                        .HasColumnType("double");

                    b.Property<int>("ERN")
                        .HasColumnType("int");

                    b.Property<double>("ETB")
                        .HasColumnType("double");

                    b.Property<double>("EUR")
                        .HasColumnType("double");

                    b.Property<double>("FJD")
                        .HasColumnType("double");

                    b.Property<double>("FKP")
                        .HasColumnType("double");

                    b.Property<double>("GBP")
                        .HasColumnType("double");

                    b.Property<double>("GEL")
                        .HasColumnType("double");

                    b.Property<double>("GGP")
                        .HasColumnType("double");

                    b.Property<double>("GHS")
                        .HasColumnType("double");

                    b.Property<double>("GIP")
                        .HasColumnType("double");

                    b.Property<double>("GMD")
                        .HasColumnType("double");

                    b.Property<double>("GNF")
                        .HasColumnType("double");

                    b.Property<double>("GTQ")
                        .HasColumnType("double");

                    b.Property<double>("GYD")
                        .HasColumnType("double");

                    b.Property<double>("HKD")
                        .HasColumnType("double");

                    b.Property<double>("HNL")
                        .HasColumnType("double");

                    b.Property<double>("HRK")
                        .HasColumnType("double");

                    b.Property<double>("HTG")
                        .HasColumnType("double");

                    b.Property<double>("HUF")
                        .HasColumnType("double");

                    b.Property<int>("IDR")
                        .HasColumnType("int");

                    b.Property<double>("ILS")
                        .HasColumnType("double");

                    b.Property<double>("IMP")
                        .HasColumnType("double");

                    b.Property<double>("INR")
                        .HasColumnType("double");

                    b.Property<double>("IQD")
                        .HasColumnType("double");

                    b.Property<double>("IRR")
                        .HasColumnType("double");

                    b.Property<double>("ISK")
                        .HasColumnType("double");

                    b.Property<double>("JEP")
                        .HasColumnType("double");

                    b.Property<double>("JMD")
                        .HasColumnType("double");

                    b.Property<double>("JOD")
                        .HasColumnType("double");

                    b.Property<double>("JPY")
                        .HasColumnType("double");

                    b.Property<double>("KES")
                        .HasColumnType("double");

                    b.Property<double>("KGS")
                        .HasColumnType("double");

                    b.Property<double>("KHR")
                        .HasColumnType("double");

                    b.Property<double>("KMF")
                        .HasColumnType("double");

                    b.Property<int>("KPW")
                        .HasColumnType("int");

                    b.Property<double>("KRW")
                        .HasColumnType("double");

                    b.Property<double>("KWD")
                        .HasColumnType("double");

                    b.Property<double>("KYD")
                        .HasColumnType("double");

                    b.Property<double>("KZT")
                        .HasColumnType("double");

                    b.Property<double>("LAK")
                        .HasColumnType("double");

                    b.Property<double>("LBP")
                        .HasColumnType("double");

                    b.Property<double>("LKR")
                        .HasColumnType("double");

                    b.Property<double>("LRD")
                        .HasColumnType("double");

                    b.Property<double>("LSL")
                        .HasColumnType("double");

                    b.Property<double>("LYD")
                        .HasColumnType("double");

                    b.Property<double>("MAD")
                        .HasColumnType("double");

                    b.Property<double>("MDL")
                        .HasColumnType("double");

                    b.Property<double>("MGA")
                        .HasColumnType("double");

                    b.Property<double>("MKD")
                        .HasColumnType("double");

                    b.Property<double>("MMK")
                        .HasColumnType("double");

                    b.Property<double>("MNT")
                        .HasColumnType("double");

                    b.Property<double>("MOP")
                        .HasColumnType("double");

                    b.Property<double>("MRU")
                        .HasColumnType("double");

                    b.Property<double>("MUR")
                        .HasColumnType("double");

                    b.Property<double>("MVR")
                        .HasColumnType("double");

                    b.Property<double>("MWK")
                        .HasColumnType("double");

                    b.Property<double>("MXN")
                        .HasColumnType("double");

                    b.Property<double>("MYR")
                        .HasColumnType("double");

                    b.Property<double>("MZN")
                        .HasColumnType("double");

                    b.Property<double>("NAD")
                        .HasColumnType("double");

                    b.Property<double>("NGN")
                        .HasColumnType("double");

                    b.Property<double>("NIO")
                        .HasColumnType("double");

                    b.Property<double>("NOK")
                        .HasColumnType("double");

                    b.Property<double>("NPR")
                        .HasColumnType("double");

                    b.Property<double>("NZD")
                        .HasColumnType("double");

                    b.Property<double>("OMR")
                        .HasColumnType("double");

                    b.Property<int>("PAB")
                        .HasColumnType("int");

                    b.Property<double>("PEN")
                        .HasColumnType("double");

                    b.Property<double>("PGK")
                        .HasColumnType("double");

                    b.Property<double>("PHP")
                        .HasColumnType("double");

                    b.Property<double>("PKR")
                        .HasColumnType("double");

                    b.Property<double>("PLN")
                        .HasColumnType("double");

                    b.Property<double>("PYG")
                        .HasColumnType("double");

                    b.Property<double>("QAR")
                        .HasColumnType("double");

                    b.Property<double>("RON")
                        .HasColumnType("double");

                    b.Property<double>("RSD")
                        .HasColumnType("double");

                    b.Property<double>("RUB")
                        .HasColumnType("double");

                    b.Property<double>("RWF")
                        .HasColumnType("double");

                    b.Property<double>("SAR")
                        .HasColumnType("double");

                    b.Property<double>("SBD")
                        .HasColumnType("double");

                    b.Property<double>("SCR")
                        .HasColumnType("double");

                    b.Property<double>("SDG")
                        .HasColumnType("double");

                    b.Property<double>("SEK")
                        .HasColumnType("double");

                    b.Property<double>("SGD")
                        .HasColumnType("double");

                    b.Property<double>("SHP")
                        .HasColumnType("double");

                    b.Property<double>("SLL")
                        .HasColumnType("double");

                    b.Property<double>("SOS")
                        .HasColumnType("double");

                    b.Property<double>("SRD")
                        .HasColumnType("double");

                    b.Property<double>("SSP")
                        .HasColumnType("double");

                    b.Property<double>("STD")
                        .HasColumnType("double");

                    b.Property<double>("STN")
                        .HasColumnType("double");

                    b.Property<double>("SVC")
                        .HasColumnType("double");

                    b.Property<double>("SYP")
                        .HasColumnType("double");

                    b.Property<double>("SZL")
                        .HasColumnType("double");

                    b.Property<double>("THB")
                        .HasColumnType("double");

                    b.Property<double>("TJS")
                        .HasColumnType("double");

                    b.Property<double>("TMT")
                        .HasColumnType("double");

                    b.Property<double>("TND")
                        .HasColumnType("double");

                    b.Property<double>("TOP")
                        .HasColumnType("double");

                    b.Property<double>("TRY")
                        .HasColumnType("double");

                    b.Property<double>("TTD")
                        .HasColumnType("double");

                    b.Property<double>("TWD")
                        .HasColumnType("double");

                    b.Property<double>("TZS")
                        .HasColumnType("double");

                    b.Property<double>("UAH")
                        .HasColumnType("double");

                    b.Property<double>("UGX")
                        .HasColumnType("double");

                    b.Property<int>("USD")
                        .HasColumnType("int");

                    b.Property<double>("UYU")
                        .HasColumnType("double");

                    b.Property<double>("UZS")
                        .HasColumnType("double");

                    b.Property<double>("VES")
                        .HasColumnType("double");

                    b.Property<double>("VND")
                        .HasColumnType("double");

                    b.Property<double>("VUV")
                        .HasColumnType("double");

                    b.Property<double>("WST")
                        .HasColumnType("double");

                    b.Property<double>("XAF")
                        .HasColumnType("double");

                    b.Property<double>("XAG")
                        .HasColumnType("double");

                    b.Property<double>("XAU")
                        .HasColumnType("double");

                    b.Property<double>("XCD")
                        .HasColumnType("double");

                    b.Property<double>("XDR")
                        .HasColumnType("double");

                    b.Property<double>("XOF")
                        .HasColumnType("double");

                    b.Property<double>("XPD")
                        .HasColumnType("double");

                    b.Property<double>("XPF")
                        .HasColumnType("double");

                    b.Property<double>("XPT")
                        .HasColumnType("double");

                    b.Property<double>("YER")
                        .HasColumnType("double");

                    b.Property<double>("ZAR")
                        .HasColumnType("double");

                    b.Property<double>("ZMW")
                        .HasColumnType("double");

                    b.Property<int>("ZWL")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rates");
                });

            modelBuilder.Entity("Exchange.Models.Menjacnica", b =>
                {
                    b.HasOne("Exchange.Models.Rates", "rates")
                        .WithMany()
                        .HasForeignKey("ratesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("rates");
                });
#pragma warning restore 612, 618
        }
    }
}
